chunkRenderPasses: 1
forcestars: false
fancyGraphics: false
cheatvoidFog: true
automatePerformance: true
fancyLight: false
showsky: true
farView: false
autosave: 0
clientLight: false
smoothFPS: false
time: 0
fastDebug: 0
randomMobTextures: true
mainMenuState: 1
chatOpacity: 0.5
fancyWater: true
betterGrass: 0
signDistance: 8
waterBiomeColors: true
forceweather: false
flightSpeedFactor: 1.0
fancyTrees: false
ambientOcclusion: false
replaceBlocks: false
brightnessSlider: 1.0
forcevoidFog: false
forcesky: false
cheatclearWater: true
fancyBiomeColors: false
delayedTooltips: true
fancyClouds: false
showvoidFog: true
viewBobbing: false
chatColorAssist: false
advancedOpenGL: 1
aaSampling: 0
renderDistance: 2
showstars: true
replaceTools: false
cheatweather: true
mipmapsPercent: 0.0
connectedTextures: false
smoothLighting: 1.0
performance: 0
fancyParticles: false
advancedOptions: true
resizedScreenshotWidth: 6000
fancyGrass: false
showweather: true
forceclearWater: false
showclearWater: false
guiScale: 0
automateMode: 2
cheatstars: true
fancyFog: false
anaglyph3D: false
resizedScreenshotHeight: 3200
resizeScreenshots: false
cheatsky: true
serverTexturePromptsEnabled: true
fancyWeather: false
hotbarQuickKeysEnabled: true
