blockedEntities: []
minimap:
    lightmap: false
    scale: false
    visible: false
    deathpoints: true
    yAdjust: 0.0
    firstrun: true
    zoom: 1
    directions: true
    scanRadius: 3
    coords: true
    color: true
    background: true
    xAdjust: 0.0
    sizeAdjust: 1.0
    showEntities: true
    heightmap: true
    cavemap: false
    square: false
